### ISSUE TITLE
Avoid duplication of work

### ISSUE THREAD

**Issue by willhbr** [tfinlay/LEARN-pdf-auto-opener#1]
Hi! I just saw your extension linked on the UCSA notice board.

I actually made an extension to solve the same problem when I was a student. [Webstore](https://chrome.google.com/webstore/detail/learn-enhancer/dnllhgllbbihefjdpamldjnlpllogkcf) and [code](https://github.com/willhbr/learn-enhancer).

You may find it helpful to look at my code - there were (and I assume still are) some edge-cases that your existing extension will not support correctly - eg. Learn will sometimes force-download a PDF, which clutters up your downloads folder and is generally annoying.

**Comment by tfinlay** [comment]
Hi, thanks for the info - your extension looks pretty complete! I've actually had that force download behaviour on my TODO list for quite a while... will definitely take a look.
